### ISSUE TITLE
Document the new Tipping feature

### ISSUE THREAD

**Issue by anthonyliriano** [gibwork/gibwork-docs#1]
Document the new tipping feature in the docs page [Tipping docs](https://github.com/gibwork/gibwork-docs/blob/main/how-it-works/tipping.md)

The documentation should be clear to both native and non-native crypto users. The audience reading this document will be open source maintainers and contributors. 

Resources on how the tipping feature works: 
- https://x.com/gib_work/status/1754627966103908751?s=20
- https://www.youtube.com/watch?v=jAqWt_fNvW4&t=821s

Feel free to ask any questions below or on Discord: https://discord.com/invite/G54VHkcuHS

**Comment by brighton-ifaya** [comment]
Hello. I have made a PR on this issue. Please review when you have time. #3 .

**Comment by DracocardZ** [comment]
a pr issuess ?? what is it

**Comment by mazzabreno** [comment]
Hello there! I've made a pull request in order to make the introduction even more clarifying.
